/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevRouteImport } from './routes/dev'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LocationSearchRouteImport } from './routes/location-search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as LegalDocSlugRouteImport } from './routes/legal.$docSlug'
import { Route as OrderSuccessOrderIdRouteImport } from './routes/order-success.$orderId'
import { Route as PartnerPartnerIdRouteImport } from './routes/partner.$partnerId'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSearchRoute = LocationSearchRouteImport.update({
  id: '/location-search',
  path: '/location-search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocSlugRoute = LegalDocSlugRouteImport.update({
  id: '/legal/$docSlug',
  path: '/legal/$docSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessOrderIdRoute = OrderSuccessOrderIdRouteImport.update({
  id: '/order-success/$orderId',
  path: '/order-success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerIdRoute = PartnerPartnerIdRouteImport.update({
  id: '/partner/$partnerId',
  path: '/partner/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dev': typeof DevRoute
  '/faqs': typeof FaqsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/location-search': typeof LocationSearchRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dev': typeof DevRoute
  '/faqs': typeof FaqsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/location-search': typeof LocationSearchRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/invoices': typeof InvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dev': typeof DevRoute
  '/faqs': typeof FaqsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/location-search': typeof LocationSearchRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/partner/$partnerId': typeof PartnerPartnerIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dev'
    | '/faqs'
    | '/help'
    | '/history'
    | '/home'
    | '/location'
    | '/location-search'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/profile'
    | '/referral'
    | '/search'
    | '/wallet'
    | '/invoices/$invoiceId'
    | '/legal/$docSlug'
    | '/order-success/$orderId'
    | '/partner/$partnerId'
    | '/services/$serviceId'
    | '/track/$orderId'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dev'
    | '/faqs'
    | '/help'
    | '/history'
    | '/home'
    | '/location'
    | '/location-search'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/profile'
    | '/referral'
    | '/search'
    | '/wallet'
    | '/invoices/$invoiceId'
    | '/legal/$docSlug'
    | '/order-success/$orderId'
    | '/partner/$partnerId'
    | '/services/$serviceId'
    | '/track/$orderId'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dev'
    | '/faqs'
    | '/help'
    | '/history'
    | '/home'
    | '/location'
    | '/location-search'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/profile'
    | '/referral'
    | '/search'
    | '/wallet'
    | '/invoices/$invoiceId'
    | '/legal/$docSlug'
    | '/order-success/$orderId'
    | '/partner/$partnerId'
    | '/services/$serviceId'
    | '/track/$orderId'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DevRoute: typeof DevRoute
  FaqsRoute: typeof FaqsRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LocationRoute: typeof LocationRoute
  LocationSearchRoute: typeof LocationSearchRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  SearchRoute: typeof SearchRoute
  WalletRoute: typeof WalletRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  LegalDocSlugRoute: typeof LegalDocSlugRoute
  OrderSuccessOrderIdRoute: typeof OrderSuccessOrderIdRoute
  PartnerPartnerIdRoute: typeof PartnerPartnerIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-search': {
      id: '/location-search'
      path: '/location-search'
      fullPath: '/location-search'
      preLoaderRoute: typeof LocationSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$docSlug': {
      id: '/legal/$docSlug'
      path: '/legal/$docSlug'
      fullPath: '/legal/$docSlug'
      preLoaderRoute: typeof LegalDocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$orderId': {
      id: '/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof OrderSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/$partnerId': {
      id: '/partner/$partnerId'
      path: '/partner/$partnerId'
      fullPath: '/partner/$partnerId'
      preLoaderRoute: typeof PartnerPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DevRoute: DevRoute,
  FaqsRoute: FaqsRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LocationRoute: LocationRoute,
  LocationSearchRoute: LocationSearchRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  SearchRoute: SearchRoute,
  WalletRoute: WalletRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  LegalDocSlugRoute: LegalDocSlugRoute,
  OrderSuccessOrderIdRoute: OrderSuccessOrderIdRoute,
  PartnerPartnerIdRoute: PartnerPartnerIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
