/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as IncentivesRouteImport } from './routes/incentives'
import { Route as InstructionRouteImport } from './routes/instruction'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const IncentivesRoute = IncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionRoute = InstructionRouteImport.update({
  id: '/instruction',
  path: '/instruction',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/incentives': typeof IncentivesRoute
  '/instruction': typeof InstructionRoute
  '/instructions': typeof InstructionsRoute
  '/language': typeof LanguageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/incentives': typeof IncentivesRoute
  '/instruction': typeof InstructionRoute
  '/instructions': typeof InstructionsRoute
  '/language': typeof LanguageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/incentives': typeof IncentivesRoute
  '/instruction': typeof InstructionRoute
  '/instructions': typeof InstructionsRoute
  '/language': typeof LanguageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deliveries'
    | '/incentives'
    | '/instruction'
    | '/instructions'
    | '/language'
    | '/leaderboard'
    | '/onboarding'
    | '/orders'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/verification'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deliveries'
    | '/incentives'
    | '/instruction'
    | '/instructions'
    | '/language'
    | '/leaderboard'
    | '/onboarding'
    | '/orders'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/verification'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deliveries'
    | '/incentives'
    | '/instruction'
    | '/instructions'
    | '/language'
    | '/leaderboard'
    | '/onboarding'
    | '/orders'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/verification'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DeliveriesRoute: typeof DeliveriesRoute
  IncentivesRoute: typeof IncentivesRoute
  InstructionRoute: typeof InstructionRoute
  InstructionsRoute: typeof InstructionsRoute
  LanguageRoute: typeof LanguageRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationRoute: typeof RegistrationRoute
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incentives': {
      id: '/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof IncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruction': {
      id: '/instruction'
      path: '/instruction'
      fullPath: '/instruction'
      preLoaderRoute: typeof InstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DeliveriesRoute: DeliveriesRoute,
  IncentivesRoute: IncentivesRoute,
  InstructionRoute: InstructionRoute,
  InstructionsRoute: InstructionsRoute,
  LanguageRoute: LanguageRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  RegistrationRoute: RegistrationRoute,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
